//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.23 at 05:01:44 PM EET 
//


package com.nixsolutions.university.ws.soap.semester;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nixsolutions.university.soap.semester package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nixsolutions.university.soap.semester
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSemesterRequest }
     * 
     */
    public GetSemesterRequest createGetSemesterRequest() {
        return new GetSemesterRequest();
    }

    /**
     * Create an instance of {@link DeleteSemesterResponse }
     * 
     */
    public DeleteSemesterResponse createDeleteSemesterResponse() {
        return new DeleteSemesterResponse();
    }

    /**
     * Create an instance of {@link CreateSemesterRequest }
     * 
     */
    public CreateSemesterRequest createCreateSemesterRequest() {
        return new CreateSemesterRequest();
    }

    /**
     * Create an instance of {@link Semester }
     * 
     */
    public Semester createSemester() {
        return new Semester();
    }

    /**
     * Create an instance of {@link UpdateSemesterRequest }
     * 
     */
    public UpdateSemesterRequest createUpdateSemesterRequest() {
        return new UpdateSemesterRequest();
    }

    /**
     * Create an instance of {@link ListSemesterRequest }
     * 
     */
    public ListSemesterRequest createListSemesterRequest() {
        return new ListSemesterRequest();
    }

    /**
     * Create an instance of {@link GetSemesterResponse }
     * 
     */
    public GetSemesterResponse createGetSemesterResponse() {
        return new GetSemesterResponse();
    }

    /**
     * Create an instance of {@link UpdateSemesterResponse }
     * 
     */
    public UpdateSemesterResponse createUpdateSemesterResponse() {
        return new UpdateSemesterResponse();
    }

    /**
     * Create an instance of {@link CreateSemesterResponse }
     * 
     */
    public CreateSemesterResponse createCreateSemesterResponse() {
        return new CreateSemesterResponse();
    }

    /**
     * Create an instance of {@link DeleteSemesterRequest }
     * 
     */
    public DeleteSemesterRequest createDeleteSemesterRequest() {
        return new DeleteSemesterRequest();
    }

    /**
     * Create an instance of {@link ListSemesterResponse }
     * 
     */
    public ListSemesterResponse createListSemesterResponse() {
        return new ListSemesterResponse();
    }

}
